project:
  type: book

book:
  title: "Advanced Statistics and Data Analysis"
  author: 
    name: "Davide Risso"
    affiliation: "Department of Statistical Sciences, University of Padova"
  date: last-modified
  chapters:
    - index.qmd
    - intro.qmd
    - dataviz.qmd
    - dataviz2.qmd
    - git.qmd
    - linmod.qmd
    - linmod2.qmd
    - design.qmd
    - glm.qmd
    - hdr.qmd
    - bayes.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

webr: 
  show-startup-message: false
  packages: ['tidyverse', 'gapminder']
  
filters:
  - webr
  
execute:
  echo: true
