project:
  type: book

book:
  title: "Advanced Statistics and Data Analysis"
  author: 
    name: "Davide Risso"
    affiliation: "Department of Statistical Sciences, University of Padova"
  date: last-modified
  chapters:
    - index.qmd
    - intro.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



