# Introduction {.unnumbered}

This is the companion website of the 2026 edition of the "Advanced Statistics and Data Analysis" course, taught within the ["Quantitative and Computational Biosciences" Master's program](https://www.unipd.it/en/educational-offer/second-cycle-degree/science?tipo=LM&scuola=SC&ordinamento=2024&key=SC2804&cg=science) at the [University of Padova](https://www.unipd.it/).

If you are looking for the materials of the 2025 edition of this course, you can find them on the [2025 branch of the github repository](https://github.com/drisso/ASDA/tree/2025).

## Organization of this website

This website is organized as a book. Each class topic is treated in a different chapter.

In each Chapter, you will find the slides presented in class and the code used for the practicals.

You can use the navigation bar to navigate by topic or the Timeline section below to see the topics in the same order they were presented in class.

## Timeline

### Lectures

| Week | Date      | Topic                                | Hours |
|------|-----------|--------------------------------------|-------|
| 1    | 23/2/2026 | Intro to course  (online)            | 2     |
|      | 24/2/2026 | Data wrangling and visualization     | 2     |
|      | 26/2/2026 | Visualizing distributions            | 2     |
|      | 27/2/2026 | Visualizing multiple variables       | 2     |
| 2    | 3/3/2026 | TBA          | 2     |
|      | 5/3/2026 | TBA              | 2     |
|      | 6/3/2026 | TBA (online)        | 4     |
| 3    | 9/3/2026 | TBA          | 2     |
|      | 10/3/2026 | TBA               | 2     |
|      | 12/3/2026 | TBA              | 2     |
|      | 13/3/2026 | TBA         | 2     |
| 5    | 23/3/2026 | TBA (online)         | 2     |
|      | 24/3/2026 | TBA               | 2     |
|      | 26/3/2026 | TBA              | 2     |
|      | 27/3/2026 | TBA         | 2     |


### Labs

| Week | Date      | Topic                                     | Hours |
|------|-----------|-------------------------------------------|-------|
| 1    | 25/2/2026 | Data wrangling and visualization (part 1) | 4     |
| 2    | 2/3/2026  | TBA | 4     |
| 3    | 4/3/2026  | TBA | 4     |
| 4    | 9/3/2026  | TBA                   | 4     |
| 5    | 11/3/2026 | TBA                    | 4     |
| 6    | 18/3/2026 | TBA                    | 4     |
| 7    | 25/3/2026 | TBA                    | 4     |
| 8    | 30/3/2026 | TBA                    | 4     |


## Suggested reading materials

### R resources

-   [R for Data Science book](https://r4ds.had.co.nz/)
-   [Tidyverse Skills for Data Science in R](https://www.coursera.org/specializations/tidyverse-data-science-r)
-   [The ggplot2 book](https://ggplot2-book.org/)
-   [Happy Git with R](https://happygitwithr.com/)
-   [Advanced R](https://adv-r.hadley.nz/)

### Statistics

- [Modern Statistics for Modern Biology](https://www.huber.embl.de/msmb/)
- [Data Analysis for the Life Sciences](https://leanpub.com/dataanalysisforthelifesciences)

## Work in progress

The book is a work in progress as we move through the first edition of this class. Please, open issues and contribute pull requests at https://github.com/drisso/ASDA if you find typos or mistakes or if something is missing.

## Acknowledgments

I wish to warmly thank all the authors that have provided open resources related to the topics of this course. In particular, the following people either directly or indirectly inspired the materials developed for this course: Claus O. Wilke, Carrie Wright, Shannon E. Ellis, Stephanie C. Hicks, Roger D. Peng, Wolfgang Huber, Susan Holmes, Hadley Wickham, Lieven Clement, Milan Malfait, Karl Broman, Rafael Irizarry, Mike Love, Jeff Leek, Brian Caffo, Charlotte Soneson.

In the same spirit, I am sharing openly online this course.

Specific resources that can be used as additional readings are noted in the relevant chapters.
